### ISSUE TITLE
Wrong command in README

### ISSUE THREAD

**Issue by nikolausmayer** [lmb-freiburg/netdef_models#1]
The README [says](https://github.com/lmb-freiburg/netdef_models/blob/master/README.md#running-networks) to execute:
`python3 controller.py image0_path image1_path out_dir`

This results in an error message. The README is missing the selection of the actual command to be executed `{eval,perf-test,list-evos,list-states}`.

**Comment by tonmoy-saikia** [comment]
Thanks! Fixed.

**Comment by nikolausmayer** [comment]
Thanks!
