### ISSUE TITLE
Error on "python3 controller.py eval image0_path image1_path out_dir"

### ISSUE THREAD

**Issue by Amirhk-dev** [lmb-freiburg/netdef_models#3]
"lmbspecialops" is built correctly and the small example (provided in [this page](https://github.com/lmb-freiburg/lmbspecialops/tree/eccv18)) ran without any error. 

By running the script below (providing the path for image0_path, image1_path and out_dir):
 python3 controller.py eval image0_path image1_path out_dir

The following error happens:

...
from lmbspecialops import correlation as correlation
ImportError: cannot import name 'correlation'

**Comment by silviogalesso** [comment]
Hi, what branch of lmbspecialops did you build? Only the eccv2018 branch contains the correlation operation.

**Comment by Amirhk-dev** [comment]
Hi, Thanks @silviogalesso , It seems like somehow I built the master branch instead of eccv2018! 
It is Solved.
