### ISSUE TITLE
FlowNetH training

### ISSUE THREAD

**Issue by luoru** [lmb-freiburg/netdef_models#4]
I just wanna to know if step training used in FlowNetH( 1st train hypNet, then mergeNet, or train the whole net ) ,  and the batch size. It can't be find in paper! Many thanks

**Comment by silviogalesso** [comment]
Hi, FlowNetH is trained much like FlowNet2, i.e. one network at a time (not end to end), and with a batch size of 8.

**Comment by luoru** [comment]
Thank for your reply！
