### ISSUE TITLE
Error on "python3 controller.py " in occ-fill

### ISSUE THREAD

**Issue by vhik4596** [lmb-freiburg/netdef_models#5]
I was trying to running the script below in `SceneFlow/occ-fill` folder:
`python3 controller.py eval --imgs_t0 test_images/t0_imgL.png test_images/t0_imgR.png --imgs_t1 test_images/t1_imgL.png test_images/t1_imgR.png --dn_path ../../DispNet3/CSS/ --fn_path ../../FlowNet3/CSS/`
But I got following error message:
`FileNotFoundError: [Errno 2] No such file or directory: '../../DispNet3/CSS/training/00__flyingThings3D.train__S_custom/checkpoints'`
I sure there is a folder in my computer named `../../DispNet3/CSS/training/00__flyingThings3D.train__S_short/checkpoints'` after `bash download_snapshots.sh`
Any solution? thanks.

**Comment by tonmoy-saikia** [comment]
Have you downloaded the snapshots for FlowNet3CSS and DispNet3CSS?

**Comment by vhik4596** [comment]
> Have you downloaded the snapshots for FlowNet3CSS and DispNet3CSS?

Yes, I have downloaded all snapshots by `bash download_snapshots.sh` in DispNet3 and FlowNet3 folder, respectively.

**Comment by tonmoy-saikia** [comment]
Looks like it is looking for the a wrong checkpoint directory.. `train__S_custom` vs `train__S_short`.
You could manually try renaming it and see it works?

**Comment by vhik4596** [comment]
Well, after I manually rename `DispNet3/CSS/training/00__flyingThings3D.train__S_short` to `DispNet3/CSS/training/00__flyingThings3D.train__S_custom`, there is a new error message:
`FileNotFoundError: [Errno 2] No such file or directory: '../../FlowNet3/CSS/training/01__flyingThings3D.train__S_short/checkpoints'`

then, I tried rename `FlowNet3/CSS/training/00__flyingThings3D.train__S_fine_half` to `FlowNet3/CSS/training/01__flyingThings3D.train__S_short/checkpoints`, another error message happened:

```
.
.
.
restoring     refine_disp/encoder/conv6_1/kernel
restoring     refine_disp/encoder/predict/conv/bias
restoring     refine_disp/encoder/predict/conv/kernel
Saving output in: None
Traceback (most recent call last):
  File "controller.py", line 128, in <module>
    controller.run()
  File "/home/mark/.local/lib/python3.5/site-packages/netdef_slim/tensorflow/controller/base_controller.py", line 36, in run
    self._command_hooks[command]()
  File "controller.py", line 121, in eval
    state=self._args.state)
  File "/home/mark/.local/lib/python3.5/site-packages/netdef_slim/tensorflow/controller/base_controller.py", line 96, in eval
    out_path = os.path.join(out_dir, k+suffix)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by vhik4596** [comment]
Hi, @tonmoy-saikia 
I tried to running the script by adding `--out_dir ./` (i.e. `python3 controller.py eval --imgs_t0 test_images/t0
_imgL.png test_images/t0_imgR.png --imgs_t1 test_images/t1_imgL.png test_images/t1_imgR.png --dn_path ../../DispNet3/CSS/ --fn_path ../../FlowNet3/CSS/ --out_dir ./`)
Then, the program works!
But, I am not sure manually rename `DispNet3/CSS/training/00__flyingThings3D.train__S_short` to `DispNet3/CSS/training/00__flyingThings3D.train__S_custom` and  `FlowNet3/CSS/training/00__flyingThings3D.train__S_fine_half` to `FlowNet3/CSS/training/01__flyingThings3D.train__S_short` affect the result or not in my computer.
Is there any groundtruth or reference that can let me check?
BTW, this is the [output](https://drive.google.com/file/d/1hxUVHIwdAOF5ckZfw3hpnVA3B3NjGrYq/view?usp=sharing) and the output meaning "predicted disp from t=1 at t=0" in the ECCV paper Fig. 1.(d), is this right?

**Comment by tonmoy-saikia** [comment]
The output looks fine to me. You can use the KITTI or FlyingThings3D dataset to compare against the ground truth.

**Comment by vhik4596** [comment]
@tonmoy-saikia Thanks!
