### ISSUE TITLE
ERROR: The certificate of ‘lmb.informatik.uni-freiburg.de’ is not trusted.

### ISSUE THREAD

**Issue by tksharpless** [lmb-freiburg/netdef_models#6]
Running download_snapshots.sh in netdef_models/dispnet3 gives the above error (multiple times).
I am using Debian bash under Windows 10.

**Comment by tksharpless** [comment]
Adding --no-check-certificate to the wget commands allows downloading with warnings.
However you really should upgrade your certifictes.

**Comment by nikolausmayer** [comment]
This issue has now finally been resolved. `wget`should no longer report certificate errors.
